// This file is autogenerated by BuildPlugins.sh


vlc_declare_plugin(dummy);
vlc_declare_plugin(filesystem);
vlc_declare_plugin(mp4);
vlc_declare_plugin(avi);
vlc_declare_plugin(avcodec);
vlc_declare_plugin(lpcm);
vlc_declare_plugin(copy);

const void *vlc_builtins_modules[] = {
    vlc_plugin(dummy),
    vlc_plugin(filesystem),
    vlc_plugin(mp4),
    vlc_plugin(avi),
    vlc_plugin(avcodec),
    vlc_plugin(lpcm),
    vlc_plugin(copy),
    NULL
};

